### ISSUE TITLE
Just misspelling actually of Techniquies 

### ISSUE THREAD

**Issue by franc-fns** [ImJohnMDaniel/at4dx-samplecode#13]
[apex-enterprise-patterns/at4dx-samplecode: Sample code demonstrating the usage of the AT4DX Framework (github.com)](https://github.com/apex-enterprise-patterns/at4dx-samplecode)

![image](https://github.com/apex-enterprise-patterns/at4dx-samplecode/assets/139787153/d333817b-e294-4aee-8cdd-cd18b85bfd62)

**Comment by ImJohnMDaniel** [comment]
Thank you @franc-fns.  We appreciate it!
